name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger:
- master

# equivalent trigger
# trigger:
#   branches:
#     include:
#     - master

variables:
  name: martin

pool:
  vmImage: ubuntu-latest

jobs:
- job: A
  steps:
  # steps omitted for brevity

- job: B
  dependsOn: A
  steps:
  # steps omitted for brevity

- job: C
  dependsOn: B
  steps:
    - script: echo "The Password is, $(password)"